### ISSUE TITLE
Request to use core WMM_Tiny files to create an Arduino Library

### ISSUE THREAD

**Issue by DavidArmstrong** [miniwinwm/WMM_Tiny#2]
Hi,
First, thank you for making this repository available, and going through the work needed to provide an embedded variation of the NOAA code.  I'm writing to request permission to use the three core C files in WMM_Tiny as part of an Arduino based library to provide the geomagnetic declination based on the users local latitude and longitude.  This would be specific to the Arduino IDE.  (I'm thinking of calling it WMM_Tinier, since it will be much smaller than your code.)  The documentation would make reference to this repository, giving recognition to your work and contributions, as well as the NOAA web site that provides the original code and coefficients files.

**Comment by miniwinwm** [comment]
Yes, no problem.

**Comment by DavidArmstrong** [comment]
Thank you.  The new repository is located at: https://github.com/DavidArmstrong/WMM_Tinier
Let me know of any issues or comments you may have with it.
