### ISSUE TITLE
Recommendations for how to modify to be a function of altitude?

### ISSUE THREAD

**Issue by patrickwalton** [miniwinwm/WMM_Tiny#3]
I'd like to use WMM for a satellite application running on Arduino ecosystem, but this library and WMM_Tinier aren't functions of altitude. Any recommendations for how to modify this library to be a function of altitude?

If I understand right, you used the wmm_cof_converter program to compress the coefficients file? Does the compression need to be changed to get attitude?

**Comment by miniwinwm** [comment]
Use the full WMM source code from NOAA, not this library. It's here...

https://www.ngdc.noaa.gov/geomag/WMM/soft.shtml

**Comment by patrickwalton** [comment]
The full WMM source code is overkill in this case. I found [another library](https://github.com/wiedehopf/readsb/blob/dev/geomag.c) that uses almost the same E0000 function as you while including altitude, but as part of a much larger collection.

Also, your approach is quite different from the NOAA full source code, which doesn't contain the E0000 function at all, for example. Can you shed some light on how you built your library?

Since NOAA links to your repo for embedded C99 applications, I think it would be good to enable altitude returns (it's like 5 lines of code and a few more arguments). Can I make a pull request for this? I already have it implemented.

**Comment by miniwinwm** [comment]
I developed this library for use on resource constrained devices in marine applications where altitude is of no interest. I'm not adding altitude back in having worked to remove it, so I won't be accepting a pull request that does that. 

My code is based on NOAA's legacy C implementation from here...

https://www.ngdc.noaa.gov/geomag/WMM/thirdpartycontributions.shtml
