### ISSUE TITLE
Faulty results on arduino due

### ISSUE THREAD

**Issue by mjsneijders** [miniwinwm/WMM_Tiny#4]
Running the following code using your WMM_Tiny library on an Arduino Due results in an output of -4.80 degrees,  while the calculator on 
https://www.ngdc.noaa.gov/geomag/calculators/magcalc.shtml#declination  returns 2 degrees E. 

do you have any idea where this almost 2.5 times difference comes from?
it must have something to do with the negative latitude.....  when i run using positive latitude and compare with the website calculator,  the results look fine

code: 
```
  uint8_t year = 22;
  uint8_t month = 3;
  uint8_t day = 4;
  
  double longitude = 52.964357;
  double latitude = -4.779369;  
  float Declination; 
  
  Serial.print("Longitude = "); Serial.println(longitude,6); 
  Serial.print("Latitude = ");  Serial.println(latitude,6); 
  Serial.println((String)"On date = "+ day + "-" + month + "-"  + year + "\n"); 
  
  wmm_init();  
  float wmmdate=wmm_get_date( year,  month,  day);
  E0000(latitude, longitude, wmmdate, &Declination); 
  
  
  Serial.println();
  Serial.println((String)"The calculated geomagnetic declination is: " + Declination + " degrees");
```

output:
```
Longitude = 52.964357
Latitude = -4.779369
On date = 4-3-22


The calculated geomagnetic declination is: -4.80 degrees
```

**Comment by mjsneijders** [comment]
never mind,  i must have had my blond genes playing up...  lat/lon reversed

**Comment by miniwinwm** [comment]
Thanks for the interest in the library anyway. I'll get on to fixing the
typo.
